dist: trusty
sudo: false
language: python
python:
  - '3.6'
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: asleao-github
    token:
      secure: "$SONAR_TOKEN"
    github_token:
      secure: "$GITHUB_TOKEN"
install:
  - pip install -r requirements.txt
script:
#  - pytest
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: heroku
  api_key:
    secure: SxNr5N2G84PrdpNhad4fDcMH7aixidURJoIWoZLQV9LX+B0xcnau28qEJtPs5PJr4nEc57sVIqEOjAzPgoIsvFG5L2Q0G0TbpVZLiaBSPEYzQ7BF6geHn+YN073X3ichCNjfhkbUpXS3EpjFdVAQiz7zwtUmWiTxDETnRvwQbEK69pp10xurVJNeab4UiKjkjYrWh6uJXe5Mf8R5kSYmJ6PFLuTpASop2QTb1zDfGAvay342ar6haH7kcXbMqk4cQNtpSKJnKRM9jfVquAch3eKhvJbdDAzRngMcdNSmFUsXuGyWBmHhl1wBHqOf8OwZ9jL+l49B8jcnHX32d5RO1i5V2JgtmV90LBh3CceZ4/aSECJrSCR2+ceqU4ezoFqPcImIQJz4jvc33iLFSS2DPJIvcLToN8WBjDZ17FIcBw9xtHZAcHQzNHc8pJ+Beol+gq6OCRuSoTg1FN7kn2OaWDnsjE0wH9J5bj47T+hdRSxDqLjVwIg54MjdEg0LozewbQWQfOn98g7Fs11M3VXhYXFPQQiuC6Hkhq54MTO+r5s8GAiv2UcGtA0l5Dlfi4gbgJCYKJVdrcdL/9HGgMKseHk0lQSSZLllGuD78SDUjiKg3eWU4x11YXbkTAQuXNxxRkNlTST19evH1JitgY4CPoflwN7+7OFazeRaAR2R7r0=
  app:
    master: leds-zeppellin-api
    develop: leds-zeppellin-api-dev
  on:
    repo: asleao/leds-zeppellin-api

notifications:
  email:
    on_success: never
    on_failure: always
