dist: trusty
sudo: false
language: python
python:
  - '3.6'
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: asleao-github
    token:
      secure: "$SONAR_TOKEN"
    github_token:
      secure: "$GITHUB_TOKEN"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: YpdkPHaV/LMqv2NlyBt7l8BB5EKkjCrDYEmfnDa5drPgvRTi2fG/XwTzHrXgS1gfbXYcSUCx5i9Yg6rE1yShTac+xWAhoIldu4SeKkcCJuFNPl86U/QZA07U5cj+C2najIimRyMAXW6TwvQ4WbA2RDFtOSKWY87No/CmAb/iSgGq9R6KNhlOuBfhsHfZDAA4S45VVRZ8mCqxrsSgHlv2qsY07/q8Veo5p1kKP2cl8R1tleQOeAUPlY0Zn12h65GYT1zGcTdlvzg2lyYerSIQYB99k6mVuAdMLElZP9GCcEqo3tDBKzDKejQp1mgHpUR3osLU0Vh0rSDoMlCzynnnsFkxc9RBGc/1Ny0rFcF5Ks4tt8rtHMjmETQzjscgtg5v8PdpoYtLeFdlp2CR9LeboFyUPAMwYJTn6YkhVYgIgdU2yi+WYUlQJFtByaQFHKOdhkWKHSGlzg9+jMtAETIceUe2mlaJc3KRnj93DbJfL3JN9Pps7Mn2WVB9p7DoF3CtQQ3qw3aTKfvMQv2CHXYwwChIgnkMbxpY4bCOWHoHLuoM2fSb5pdM26yvR24A5N+6dHqWQRT8uXrbopOn/1bFPIAi3kVVKqPL3DEmr+08yrNiifl25Gf32qUUNtFXHG8zroJ5hq2E8OdVJpJPhLO7Y6Std3vxpI8567raNwuO4MM=
  app:
    master: leds-zeppellin-api
    develop: leds-zeppellin-api-dev
  on:
    repo: asleao/leds-zeppellin-api

notifications:
  email:
    on_success: never
    on_failure: always
