dist: trusty
sudo: false
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: asleao-github
    token:
      secure: "$SONAR_TOKEN"
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
after_deploy:
- git clean -df
deploy:
  provider: heroku
  api_key:
    secure: rlpXiYGd4Z6JCKFmtyG5EyB1eUVebw9rVSkDf/OiJsDglrnnAbPQgb2sPilmJk/6eEU7UKDqLfJRGSHRIeL3fD9VfCET1XMyPKZXdHF935OjSx9hIdjvIAkuVZ44SP9eNJZHxtgWd9gJg27LrInLxnWfF0Gz8knytu8mmHpH1BQffKtyi8QAvSJAmVyfwp5NysOJtQl37uLvlIrZTT4fKc+HsFUS2pVU1L6jvK5TlU5d/Lt/BTVvXM0+0s3XQFCPm9NK0eH/iUvqznAwoYSaz/T3BbQ0GZZz1v0IkH8zyyn5wK80gx6+LtyXm9jpohL1yzR78fCnSZB5MdoXhNZcN/oolBMaED+aeKK1eO7DUCipmG4i3LOX22plPNvDKUnxKFr4A3tI7Yq8aMvgh0ued0RYBkIfag15n5GpfVjTNU+Yzb4RqoupO86lWBo8hii6/HWbUrLdIh7pqLejJO1iPsmyAEWo98nyb8QHsNcokkUXQj/cY5cD1ivb37CPyBNYsqoFH6ut4tVKZ8ICfEscL/9y/03mtzic6xqp/JtHrBaE4q9rZ4beTvcLyCGeBSfqLcyBt1RqRvZ85NWw9uHLQ0kb8LQutYuOjq7P4+hSvbRAcQW9o2fcgvjQaT4h+boqYpdtRwRQPkTzqcy7F0j7rWBU6405pTUlrXv1mPuUziA=
  app: ledszeppelin
  on:
    repo: asleao/leds-zeppelin
